version: 0.2
phases:
    install:
        runtime-versions:
            nodejs: 12
    pre_build:
        commands:
            - 'yarn install --frozen-lockfile'
    build:
        commands:
            - 'gatsby build --no-color'
artifacts:
    base-directory: public
    files:
        - '**/*'
cache:
    paths:
        - '.cache/*'
        - 'public/*'