version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - yarn --frozen-lockfile
  build:
    commands:
      - yarn build
artifacts:
  base-directory: public
  files:
    - '**/*'
cache:
  paths:
    - 'node_modules/**/*'