version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - curl -Ls $HUGO_URL -o /tmp/hugo.tar.gz
      - echo $HUGO_SHA256 /tmp/hugo.tar.gz | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
      - git clone $THEME_REPO themes/Alys
      - aws s3 rm s3://$BUCKET_PATH --recursive --exclude ""
  build:
    commands:
      - hugo
  post_build:
    commands:
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'

artifacts:
  files:
    - '**/*'
  base-directory: public