version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - curl -Ls $HUGO_URL -o /tmp/hugo.tar.gz
      - echo $HUGO_SHA256 /tmp/hugo.tar.gz | sha256sum -c -
      - tar xf /tmp/hugo.tar.gz -C /tmp
      - mv /tmp/hugo /usr/bin/hugo
      - rm -rf /tmp/hugo*
  build:
    commands:
      - hugo
  post_build: 
    commands:
      - aws s3 sync public s3://$S3_BUCKET --delete --cache-control max-age=3600
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths '/*'