version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - ls -d $PWD/node_modules
      - yarn --verbose --frozen-lockfile
  build:
    commands:
      - yarn build
artifacts:
  base-directory: public
  files:
    - '**/*'
cache:
  paths:
    - node_modules