steps:
- name: 'gcr.io/kaniko-project/executor:latest'
  id: 'build-container'
  entrypoint: 'sh'
  args:
  - --destination=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA
  - --cache=true
  - --cache-ttl=48h
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'update-service'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--image'
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
  - '--region'
  - '$_DEPLOY_REGION'
  - '--platform'
  - 'managed'
