steps:
  - id: Fetch cache
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        (
          set -e
          gsutil hash -h yarn.lock | grep md5 | tr -s " " | awk '{print $3}' > hashed.yarn-lock
          gsutil -m cp "gs://$_CACHE_BUCKET/$(cat hashed.yarn-lock)" cache.tar.gz 2> /dev/null
          test -f cache.tar.gz
          tar -zxf cache.tar.gz
          echo "Using cache from: gs://$_CACHE_BUCKET/$(cat hashed.yarn-lock)"
        ) || true
  - id: Yarn build
    name: $_NODE_IMAGE
    entrypoint: sh
    args:
      - -c
      - |
        test -f cache.tar.gz || yarn install --prod --frozen-lockfile
        yarn build
    env:
      - GATSBY_TELEMETRY_DISABLED=true
      - GATSBY_FORM_ENDPOINT=${_GATSBY_FORM_ENDPOINT}
      - GATSBY_BASIC_AUTH=${_GATSBY_BASIC_AUTH}
  - name: gcr.io/cloud-builders/docker
    id: Tag and push image
    entrypoint: sh
    args:
      - -c
      - |
        docker build --build-arg CADDY_IMAGE=$_CADDY_IMAGE -t $_APP_IMAGE:$SHORT_SHA .
        docker push $_APP_IMAGE:$SHORT_SHA
  - id: Update Cloud Run service
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        gcloud run services update $_SERVICE --platform=managed \
          --image=$_APP_IMAGE:$SHORT_SHA --region=$_REGION --quiet --async
  - id: Cache node_modules
    name: gcr.io/cloud-builders/gcloud
    entrypoint: sh
    args:
      - -c
      - |
        (
          set -e
          test ! -f cache.tar.gz
          tar -zcf cache.tar.gz node_modules public .cache
          gsutil -m cp cache.tar.gz "gs://$_CACHE_BUCKET/$(cat hashed.yarn-lock)"
        ) || true
    waitFor:
      - Yarn build