steps:
  - id: Prep SSH
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        echo "$$SECRET_KEY" >> /root/.ssh/id_ed25519 && chmod 400 /root/.ssh/id_ed25519
        ssh-keyscan -p 2022 source.developers.google.com > /root/.ssh/known_hosts
    secretEnv:
      - SECRET_KEY
    volumes:
      - name: ssh
        path: /root/.ssh
  - id: Update manifests
    name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        git clone -b dev $_CONFIG_REPO tmp && cd tmp && \
        git checkout -b master && git pull origin master && \
        git merge dev && \
        git push origin master
    volumes:
      - name: ssh
        path: /root/.ssh
availableSecrets:
  secretManager:
    - versionName: projects/$_PROJECT/secrets/$_SECRET_KEY/versions/latest
      env: SECRET_KEY