steps:
- name: 'gcr.io/cloud-builders/npm'
  args: [
          'install'
        ]
- name: gcr.io/cloud-builders/docker
  args: [
          'build',
          '-t', 'us.gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest',
          '.'
        ]
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: gcloud
  args: [
          'run',
          'deploy', '$_SERVICE_NAME',
          '--image=us.gcr.io/$PROJECT_ID/$_SERVICE_NAME:latest',
          '--region=$_DEPLOY_REGION',
          '--platform=managed'
        ]
