steps:
- name: 'gcr.io/cloud-builders/yarn'
  args: [
          'install',
          '--production=true'
        ]
- name: 'gcr.io/cloud-builders/yarn'
  args: [
          'build'
        ]
- name: gcr.io/cloud-builders/docker
  args: [
          'build',
          '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA',
          '.'
        ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
          'run',
          'deploy', '$_SERVICE_NAME',
          '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA',
          '--region=$_DEPLOY_REGION',
          '--platform=managed'
        ]
