steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'build-gatsby-container'
  args: ['build', '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA', '.']
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  id: 'update-service'
  entrypoint: gcloud
  args:
  - 'run'
  - 'deploy'
  - '$_SERVICE_NAME'
  - '--image'
  - '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'
  - '--region'
  - '$_DEPLOY_REGION'
  - '--platform'
  - 'managed'
image: '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:$SHORT_SHA'