steps:
- name: gcr.io/cloud-builders/docker
  args: [
          'build',
          '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:latest',
          '.'
        ]
- name: 'gcr.io/cloud-builders/gcloud'
  args: [
          'run',
          'deploy', '$_SERVICE_NAME',
          '--image=$_GCR_HOSTNAME/$PROJECT_ID/$_SERVICE_NAME:latest',
          '--region=$_DEPLOY_REGION',
          '--platform=managed'
        ]
