baseURL: https://misterorion.com
languageCode: en-us
title: Orion Anderson
theme: Alys
sectionPagesMenu: main
preserveTaxonomyNames: true
enableRobotsTXT: true

googleAnalytics: UA-27884057-5
permalinks:
  posts: /posts/:year/:slug/

markup:
  highlight:
    style: rrt

Params:
  authorName: Orion Anderson
  twitter: MisterOrion
  github: MisterOrion
  linkedin: orionanderson
  email: orion@mechapower.com
  authorPic: me3.jpg
  brandImg: favicon.png
  iconSize: 35
