baseURL: https://misterorion.com
languageCode: en-us
title: Orion Anderson
theme: Alys

Params:
  authorName: Orion Anderson
  twitter: MisterOrion
  github: MisterOrion
  linkedin: orionanderson
  email: orion@mechapower.com
  authorPic: me3.jpg
  brandImg: favicon.png
  iconSize: 35
  
permalinks:
  posts: /posts/:year/:slug/

sectionPagesMenu: main
preserveTaxonomyNames: true
GoogleAnalytics: UA-27884057-5
enableRobotsTXT: true
pygmentsUseClasses: true
pygmentsCodeFences: true