apiVersion: apps/v1
kind: Deployment
metadata:
  name: misterorion-com
  namespace: default
  labels:
    app: misterorion-com
spec:
  replicas: 2
  selector:
    matchLabels:
      app: misterorion-com
  template:
    metadata:
      labels:
        app: misterorion-com
    spec:
      nodeSelector:
        cloud.google.com/gke-spot: "true"
      containers:
      - name: misterorion-com
        image: us-central1-docker.pkg.dev/mechapower/apps/misterorion-com:9bc2c01
        resources:
          limits:
            memory: 24Mi
          requests:
            cpu: 5m
            memory: 6Mi
        readinessProbe:
          httpGet:
            path: /robots.txt
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /robots.txt
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: misterorion-com
  annotations:
    cloud.google.com/neg: '{"exposed_ports": {"80": {"name": "misterorion-com-ug722rt"}}}'
spec:
  type: ClusterIP
  selector:
    app: misterorion-com
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80